### ISSUE TITLE
Environment variable existing but set to value other than true or false causes toggle to be false

### ISSUE THREAD

**Issue by cyphactor** [codebreakdown/togls#21]
Today a user reported to me that they had a situation where they had an environment variables set to empty string and it was overriding their Group rule to always have it evaluate at `false`. They didn't like this behavior because apps generally don't detect removal of environment variables from `/etc/environment`, a very common place to set environment variables. So, to remove an environment variable from some environment they would have to also `unset` that exported environment variable, and restart their Ruby application to have `ENV` properly set to the new state of the environment variables.

Instead it was suggested that it would be ideal if the environment override only overrode the status of the toggle if it was explicitly set to "true" or explicitly set to "false". This would theoretically enable the environment variable to still exist but be set to some value other than "true" or "false" to have it ignored by Togls. They would still have set the environment variable to some other value other than "true" or "false" of course and they would have to restart their Ruby application to have ENV properly set to the new state of the environment variables.

To me it seems like the same number of steps.

1. Either unset exported environment variable or Export env var to some val other than "true" or "false"
2. Restart Ruby application to have `ENV` properly set to the new state of the env variables.

I think in this users case the reason that the "`unset` exported environment variable" was less of an option was because their `/etc/environment` file is managed by chef/puppet and therefore there is no easy way as part of the deployment with what they have setup to `unset` an environment variable.

Beyond that environment variables are loaded and cached per shell instance, and in the app instance. So, they would have to unset it in the shell instance that matters and then restart the application.

@BRIMIL01 @RyanHedges you guys have any thoughts/opinions on this?

**Comment by cyphactor** [comment]
@BRIMIL01 thoughts?

**Comment by cyphactor** [comment]
@RyanHedges thoughts?

**Comment by BRIMIL01** [comment]
@cyphactor @RyanHedges I think we should only accept the strings "true" and "false" as valid for environment variable togls. Anything that is invalid will indicate that the registered togl is invalid and should be skipped.

**Comment by cyphactor** [comment]
Sounds good to me.

**Comment by RyanHedges** [comment]
:+1:

**Comment by cyphactor** [comment]
This has been resolved.
