### ISSUE TITLE
Fix the target_type checking, it is still incorrect

### ISSUE THREAD

**Issue by cyphactor** [codebreakdown/togls#69]
The use of `any` as a `target_type` for features which don't have a `target_type` is very confusing and I believe is partially the reason for this not being implemented correctly in the first place. Hence, we should actually formalize a `target_type` of `Togls::TargetTypes::NONE` and appropriately update the truth table below as well as the logic in the code to make sense.

Currently we have a truth table that looks like this which I believe is wrong.

```
    # feature target type | rule target type | match?
    # ------------------------------------------------
    # any (aka none)      | any              | true
    # something (foo)     | any              | true
    # any (aka none)      | something (foo)  | false
    # something (foo)     | something (foo)  | true
    # something (foo)     | something (bar)  | false
```

If we make the changes of adding the formalized `NONE` type I think it will help us identify what states were missed or implemented incorrectly.

```
    # feature target type | rule target type | match?
    # ------------------------------------------------
    # NONE                | NONE             |
    # NONE                | ANY              |
    # NONE                | something (foo)  |
    # ANY                 | ANY              |
    # ANY                 | something (foo)  |
    # ANY                 | NONE             |
    # something (foo)     | NONE             | 
    # something (foo)     | ANY              |
    # something (foo)     | something (foo)  |
    # something (bar)     | something (foo)  |

```

**Comment by cyphactor** [comment]
After talking this through we decided that there should be the following types with the following meanings.

## Abstract Formalized Target Types

Abstract formalized types are abstract because they are made up abstract concepts, they are formalized because they are formally defined, and they are used to describe the type of the target for a given Rule, Rule Type, or Feature.

## Rule/Rule Type

**NONE** - guarantee the rule doesn't need a target to evaluate properly
**:foo** - guarantee the rule needs a target of the explicit type `:foo` to evaluate properly
**null** - guarantee not set

## Feature

**NONE** - guarantee no target will be passed when feature is evaluated
**:foo** - guarantee a target of explicit type `:foo` will be passed when feature is evaluated
**null** - guarantee not set

## Defaults

We decided that Features shouldn't have a default or maybe should have an initialization default of "not set (aka null)" but it shouldn't ever be in that state as we are going to change the API to require that when a feature is defined a target_type must be specified.

We also decided that Rules shouldn't have a default and instead should just fall back to a state of "not set  (aka null)".

## Truth Table

This gives us a truth table that looks something like the following in actuality.

```
    # feature target type | rule target type | match? | notes
    # -------------------------------------------------------
    # NOT_SET             | NOT_SET          | false  | broken - shouldn't happen
    # NOT_SET             | NONE             | true   |
    # NOT_SET             | something (foo)  | false  | broken - shouldn't happen
    # NONE                | NONE             | true   |
    # NONE                | something (foo)  | false  |
    # NONE                | NOT_SET          | false  | broken - shouldn't happen
    # something (foo)     | NONE             | true   |
    # something (foo)     | something (foo)  | true   |
    # something (foo)     | NOT_SET          | false  | broken - shouldn't happen
    # something (foo)     | something (bar)  | false  |
    # something (bar)     | something (foo)  | false  |
```

**Note:** There are broken states that technically shouldn't happen but we need to handle both in the scenarios of a rule being assigned to a feature in code and a rule being reconstituted and assigned to a feature from some remote repository.

In the assigned in code scenario we can change the API for defining a feature to require a `target_type`. We can also change the `feature(:foo).on(somerule)` API to raise an exception if the rule it is given doesn't have a `target_type`.

In the case of reconstitution of a rule and association we can't just blow up with an exception because that would break peoples applications. So, we need to instead identify the problem, log it, and evaluate to the somewhat sane default of `false` evaluation using maybe a unique null toggle style response.

**Comment by cyphactor** [comment]
Thinking about things that need to happen for these changes to take effect in no particular order.

- [ ] formalize the NOT_SET and NONE types in the code base
- [ ] modify rule types to have them default their target_type to NOT_SET
- [ ] modify rules to have them default their target_type to NOT_SET
- [ ] change the `target_match?` method logic based on new truth table
- [ ] add identification and logging of broken states for reconstitution of rules and toggles
- [ ] modify the feature definition API to require a `target_type` when a feature is specified
- [ ] modify the in code feature rule association API to require a `target_type` when a rule is associated

So thinking about this more in terms of the API and the above changes our new in code DSL would look something like the follow.

```ruby
Togls.release do
  feature(:foo, 'some foo desc', target_type: Togls::TargetTypes::NONE)
end
```

vs.

```ruby
Togls.release do
  feature(:foo, 'some foo desc')
end
```

I am not sure I am actually happy with that DSL. May need some additional thinking around this.

**Comment by cyphactor** [comment]
Guess it could be

```ruby
Togls.release do
  feature(:foo, 'some foo desc', Togls::TargetTypes::NONE)
end
```

Still not sure I am happy with that DSL.

**Comment by RyanHedges** [comment]
```
Togls.release do
  feature(:foo, 'some foo desc').target_type(Togls::TargetTypes::NONE).on
end
```

**Comment by cyphactor** [comment]
The above example makes it seem like `target_type` is optional. Revisiting the idea that it is a required thing for defining a feature. Instead after discussing it in person we feel that it should be a configuration value `default_target_type` that is used for Feature definitions when you don't include the optional target_type argument.

This allows us to maintain the following DSL in the majority of cases.

```ruby
Togls.default_feature_target_type = Togls::TargetTypes::NONE

Togls.release do
  feature(:foo, 'some foo desc')
end
```

**Comment by cyphactor** [comment]
This now gives us a task list of the following:

- [ ] formalize the NOT_SET and NONE types in the code base
- [ ] modify rule types to have them default their target_type to NOT_SET
- [ ] modify rules to have them default their target_type to NOT_SET
- [ ] change the `target_match?` method logic based on new truth table
- [ ] add identification and logging of broken states for reconstitution of rules and toggles
- [ ] modify the in code feature rule association API to require a `target_type` when a rule is associated
- [ ] add default_feature_target_type to be used by feature definition process, if not configured then raise an exception when defining a feature without a specified target_type.

**Comment by RyanHedges** [comment]
These have been completed.
