### ISSUE TITLE
Add railtie and generator to create togls config file

### ISSUE THREAD

**Issue by BRIMIL01** [codebreakdown/togls#7]
To better integrate with rails applications there should be an initalizer that reads the config from a well known location and a generator to create that config file.

**Comment by cyphactor** [comment]
I thought about this but it doesn't really fit in the scope of this gem. It would need to be part of a `togls-rails` gem or something.

**Comment by BRIMIL01** [comment]
Are there enough rails specific concerns to warrant a separate gem?

**Comment by cyphactor** [comment]
We shouldn't bake any rails specific concerns into this gem in my mind. It should work with stock ruby.

If you are talking about having rails specific concerns baked into this gem with conditional checks for presence of `Rails` constant or something. Maybe, that would be ok. Still feels wrong to me, but maybe.

**Comment by BRIMIL01** [comment]
Just include generators and a railtie. Pretty much all the stuff you listed in the readme for integration handled by the gem and loaded when rails is detected.

**Comment by cyphactor** [comment]
Yeah, I guess I would be ok with that magic assuming we can do it easily while still allowing it to work with plain old ruby projects.

**Comment by cyphactor** [comment]
After more thought about this and evolution of the Togls I believe I am now of the opinion that adding in the rails specific concerns doesn't fit in with the philosophy of this gem, specifically the avoiding magic. Also, I don't believe there are really Rails specific concerns.

**Comment by cyphactor** [comment]
Due to inactivity I am closing this issue.
