### ISSUE TITLE
In code rule and feature mismatch when defined

### ISSUE THREAD

**Issue by RyanHedges** [codebreakdown/togls#79]
```ruby
alpha_users = Togls::Rules::Group.new([1,23,], target_type: :user_id)
Togls.release do
  # Should raise an exception that target types do not match
  feature(:foo, 'desc', target_type: :user).on(alpha_users)
end
```

We need to raise an exception when the target types of a rule and a feature do not match correctly. This will help ensure the in code state of the toggle to be correct.

**Comment by cyphactor** [comment]
This feature seems to have already been implemented see, https://github.com/codebreakdown/togls/blob/master/spec/togls_spec.rb#L210-L242.

Therefore, I am closing this issue.
